from typing import TypedDict, List, Dict, Any, Optional

class AthleteProfile(TypedDict):
    age: int
    gender: str
    weight_kg: float
    height_cm: int
    transition_race_1: str
    transition_date_1: str
    target_race: str
    target_date: str
    pb_half_marathon: str
    pb_10k: str
    running_experience: str
    shoe_used: str
    shoe_mileage: float
    hr_max: int
    rhr_baseline: int
    sleep_hr_baseline: int
    runs_per_week: int
    weekly_volume_km: float
    easy_pace: str

class AgentState(TypedDict):
    """
    Defines the shared memory state of the multi-agent system.
    """
    # User Identification
    user_id: int
    
    # Raw Inputs
    message_text: Optional[str]
    file_path: Optional[str]
    file_type: Optional[str]  # "fit", "gpx", etc.
    image_data: Optional[str]  # Base64 encoded image string
    
    # Parsed Inputs
    parsed_workout: Optional[Dict[str, Any]]
    parsed_metrics: Optional[Dict[str, Any]]
    parsed_nutrition: Optional[Dict[str, Any]]
    
    # Historical Data from Database
    recent_workouts: List[Dict[str, Any]]
    recent_metrics: List[Dict[str, Any]]
    recent_insights: List[Dict[str, Any]]
    
    # Agent Outputs
    readiness_data: Optional[Dict[str, Any]]        # Generated by Physiologist
    next_workout_plan: Optional[Dict[str, Any]]     # Generated by Trainer (legacy single workout)
    weekly_plan: Optional[Dict[str, Any]]           # Generated by Trainer (new: full 4-session week)
    performance_profile: Optional[Dict[str, Any]]  # Athlete performance metrics summary
    nutrition_advice: Optional[Dict[str, Any]]      # Generated by Nutritionist
    
    # System & Routing Info
    router_decision: str  # Current routing target
    next_nodes: List[str]  # Queue of nodes to visit next
    response_message: str  # Final output to send back to the user
    
    # Athlete Profile
    athlete_profile: AthleteProfile
